name: MacOS
on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches: [ mac-gcc ]

jobs:
  macos:
    #needs: [clang_tidy]
    strategy:
      matrix:
        config:
          - release
          #- debug
        compiler:
          #- clang
          - gcc9
    name: MacOS ${{ matrix.config }} ${{ matrix.compiler }}
    runs-on: macOS-latest
    steps:
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)" && \
        export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH";
        if [ ${{ matrix.compiler }} = "gcc9" ] ; then brew install gcc@9 ; fi
        brew install ccache glew ninja sdl2 sdl2_image sdl2_mixer sdl2_ttf
        if [ ${{ matrix.compiler }} = "gcc9" ] ; then brew install --cc=gcc-9 boost ; else brew install boost ; fi
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Building
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh ${{ matrix.compiler }} ${{ matrix.config }} ../
        DMGPATH="$(pwd)"
        DMGFILE="$(ls *.dmg)"
        echo "DMG file is: $DMGPATH/$DMGFILE"
        mv $DMGFILE ${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}.dmg

    - name: Uploading DMG
      uses: actions/upload-artifact@v2
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} AppImage
        path: ${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}.dmg
