name: Visual Studio

on:
  push:
    branches: [ visualstudio ]

jobs:
  visualstudio:
    name: Dependencies
    runs-on: windows-latest
    steps:
    - name: Test
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build something requiring CL.EXE
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" ..
        nmake

# C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
# https://github.com/marketplace/actions/enable-developer-command-prompt
